services:
  bookmarks:
    build:
      tags:
        - "bookmarks:${version}"
    ports:
      - "8080:8080"
    volumes:
      - data:/var/lib
    env_file:
      - path: .env
        required: false
    restart: always

volumes:
  data:
