services:
  bookmarks:
    image: bookmarks:latest
    ports:
      - "8080"
    volumes:
      - "bookmarks_data:/var/lib"
    restart: unless-stopped
    labels:
      - traefik.http.routers.app.rule=Host(`bm.leskowsky.net`)

volumes:
  bookmarks_data:
