services:
  bookmarks:
    image: bookmarks:latest
    ports:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookmarks.rule=Host(`bm.localhost`)"
      - "traefik.http.routers.bookmarks.entrypoints=web"
