spring.datasource.url=jdbc:h2:mem:bookmarks
spring.datasource.username=SA
spring.datasource.password=
server.forward-headers-strategy=framework
server.servlet.session.timeout=-1
server.servlet.session.cookie.max-age=400d
SecurityConfiguration.userName=user
SecurityConfiguration.password=password
