---

- hosts: all
  tasks:
    - name: Checkout code
      git:
        repo: https://github.com/cleskowsky/bookmarks.git
        dest: "/opt/bookmarks@{{ git_version }}"

    - name: Update symlink
      file:
        src: "/opt/bookmarks@{{ git_version }}"
        dest: /opt/bookmarks
        state: link

    - name: Write env file
      copy:
        content: |
          spring.datasource.url=jdbc:h2:file:/var/lib/bookmarks.db
          SecurityConfiguration.userName={{ user }}
          SecurityConfiguration.password={{ password }}
          version={{ git_version }}
          TRAEFIK_CERTIFICATESRESOLVERS_BOOKMARKS_ACME_EMAIL={{ vault_letsencrypt_acme_email }}
        dest: /opt/bookmarks/.env
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: Update app
      shell: |
        cd /opt/bookmarks
        docker compose stop
        docker compose up -d --build
