---

- hosts: all
  tasks:
    - name: Checkout bookmarks
      git:
        repo: https://github.com/cleskowsky/bookmarks.git
        version: 12-deploy-bookmarks
        dest: /opt/bookmarks

    - name: Write bookmarks config
      copy:
        content: |
          spring.datasource.url=jdbc:h2:file:/var/lib/bookmarks.db
          spring.datasource.password=
          SecurityConfiguration.userName={{ user }}
          SecurityConfiguration.password={{ password }}
        dest: /opt/bookmarks/.env
        mode: 0600

    - name: Build container image
      docker_image:
        name: bookmarks
        tag: latest
        source: build
        build:
          path: /opt/bookmarks
