---

- hosts: all
  tasks:
    - name: Checkout bookmarks
      git:
        repo: https://github.com/cleskowsky/bookmarks.git
        dest: "/opt/bookmarks@{{ git_version }}"

    - name: Write app env
      copy:
        content: |
          spring.datasource.url=jdbc:h2:file:/var/lib/bookmarks.db
          spring.datasource.password=
          SecurityConfiguration.userName={{ user }}
          SecurityConfiguration.password={{ password }}
          version={{ git_version }}
        dest: /opt/bookmarks/.env
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: Build container image
      docker_image:
        name: bookmarks
        tag: "{{ git_version }}"
        source: build
        build:
          path: /opt/bookmarks

    - name: Replace app container
      shell: |
        cd /opt/bookmarks
        docker compose stop
        docker compose rm
        docker compose up -d --build
