---

- hosts: all
  vars:
    docker_users:
      - ubuntu
  roles:
    - geerlingguy.docker
  tasks:
    - name: Apt install packages
      apt:
        pkg:
          - python3-pip
          - fail2ban

    - name: Start fail2ban
      systemd_service:
        state: started
        enabled: yes
        name: fail2ban

    - name: Install python docker mod
      pip: name=docker

    - name: Checkout bookmarks
      git:
        repo: https://github.com/cleskowsky/bookmarks.git
        version: 12-deploy-bookmarks
        dest: /opt/bookmarks

    - name: Write bookmarks config
      copy:
        content: |
          spring.datasource.url=jdbc:h2:file:/var/lib/bookmarks.db
          SecurityConfiguration.userName={{ user }}
          SecurityConfiguration.password={{ password }}
        dest: /opt/bookmarks/.env
        mode: 0600

    - name: Build, run bookmarks
      docker_compose_v2:
        project_src: /opt/bookmarks
